// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccessDevice: typeof import('./src/views/managments/ManageDevices/AccessDevice.vue')['default']
    BaseCommand: typeof import('./src/components/TermBody/TermCommand/BaseCommand.vue')['default']
    DashBoard: typeof import('./src/views/DashBoard.vue')['default']
    EditDevice: typeof import('./src/views/managments/ManageDevices/EditDevice.vue')['default']
    EditGroup: typeof import('./src/views/managments/ManageGroups/EditGroup.vue')['default']
    EditOffice: typeof import('./src/views/managments/ManageOffices/EditOffice.vue')['default']
    EditScript: typeof import('./src/views/managments/ManageScripts/EditScript.vue')['default']
    EditUser: typeof import('./src/views/managments/ManageUsers/EditUser.vue')['default']
    EmptyLayout: typeof import('./src/components/layouts/EmptyLayout.vue')['default']
    HistoryCommand: typeof import('./src/components/TermBody/TermCommand/HistoryCommand.vue')['default']
    InputCommand: typeof import('./src/components/TermBody/TermCommand/InputCommand.vue')['default']
    LargeButton: typeof import('./src/components/buttons/LargeButton.vue')['default']
    LoginPage: typeof import('./src/views/LoginPage.vue')['default']
    ManageDevices: typeof import('./src/views/managments/ManageDevices.vue')['default']
    ManageDevicesCard: typeof import('./src/components/cards/ManageDevicesCard.vue')['default']
    ManageGroups: typeof import('./src/views/managments/ManageGroups.vue')['default']
    ManageGroupsCard: typeof import('./src/components/cards/ManageGroupsCard.vue')['default']
    ManageOffices: typeof import('./src/views/managments/ManageOffices.vue')['default']
    ManageScripts: typeof import('./src/views/managments/ManageScripts.vue')['default']
    ManageScriptsCard: typeof import('./src/components/cards/ManageScriptsCard.vue')['default']
    ManageUsers: typeof import('./src/views/managments/ManageUsers.vue')['default']
    NavLayout: typeof import('./src/components/layouts/NavLayout.vue')['default']
    NewDevice: typeof import('./src/views/managments/ManageDevices/NewDevice.vue')['default']
    NewGroup: typeof import('./src/views/managments/ManageGroups/NewGroup.vue')['default']
    NewOffice: typeof import('./src/views/managments/ManageOffices/NewOffice.vue')['default']
    NewScript: typeof import('./src/views/managments/ManageScripts/NewScript.vue')['default']
    NewUser: typeof import('./src/views/managments/ManageUsers/NewUser.vue')['default']
    PostOffice: typeof import('./src/components/cards/PostOffice.vue')['default']
    ReturnButton: typeof import('./src/components/buttons/ReturnButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanCard: typeof import('./src/components/cards/ScanCard.vue')['default']
    ScanEquipments: typeof import('./src/views/managments/ScanEquipments.vue')['default']
    SearchField: typeof import('./src/components/input/SearchField.vue')['default']
    SideNavBar: typeof import('./src/components/layouts/SideNavBar.vue')['default']
    TermBody: typeof import('./src/components/TermBody/TermBody.vue')['default']
    TermContainer: typeof import('./src/views/TermContainer.vue')['default']
    TermHeader: typeof import('./src/components/TermHeader/TermHeader.vue')['default']
    TermHelp: typeof import('./src/components/common/TermHelp.vue')['default']
    TermMessage: typeof import('./src/components/TermMessage/TermMessage.vue')['default']
    TermScript: typeof import('./src/components/common/TermScript.vue')['default']
    TermWelcome: typeof import('./src/components/common/TermWelcome.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    UsersCard: typeof import('./src/components/cards/UsersCard.vue')['default']
  }
}
